spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
        format_sql: true
  sql:
    init:
      mode: always
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:shareit
    username: test
    password: test
  #datasource:
    #driverClassName: org.postgresql.Driver
    #url: jdbc:postgresql://localhost:5432/shareit
    #username: shareit_user
    #password: shareit_password
