CREATE TABLE IF NOT EXISTS users
(
    id    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name  VARCHAR(255) NOT NULL,
    email VARCHAR(320) NOT NULL,
    UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS requests
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    description  TEXT                          NOT NULL,
    requestor_id INTEGER REFERENCES users (id) NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_requests_users FOREIGN KEY (requestor_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS items
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  TEXT         NOT NULL,
    is_available BOOLEAN      NOT NULL,
    owner_id     INTEGER      NOT NULL,
    request_id   INTEGER,
    CONSTRAINT fk_items_users FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT fk_items_requests FOREIGN KEY (request_id) REFERENCES requests (id)
);

CREATE TABLE IF NOT EXISTS comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      TEXT    NOT NULL,
    item_id   INTEGER NOT NULL,
    author_id INTEGER NOT NULL,
    created_at   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_comments_items FOREIGN KEY (item_id) REFERENCES items (id) on delete cascade,
    CONSTRAINT fk_comments_users FOREIGN KEY (author_id) REFERENCES users (id) on delete cascade
);

CREATE TABLE IF NOT EXISTS bookings
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    start_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITHOUT TIME ZONE,
    item_id    INTEGER                     NOT NULL,
    booker_id  INTEGER                     NOT NULL,
    status     VARCHAR(8)                  NOT NULL,
    CONSTRAINT fk_bookings_items FOREIGN KEY (item_id) REFERENCES items (id),
    CONSTRAINT fk_bookings_users FOREIGN KEY (booker_id) REFERENCES users (id)
);